<?php

namespace AppBundle\Repository;

/**
 * CicloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CicloRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByDate($startDate, $endDate)
    {	

	    // $emConfig = $this->getEntityManager()->getConfiguration();
	    // $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
	    // $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
	    // $emConfig->addCustomDatetimeFunction('DAY', 'DoctrineExtensions\Query\Mysql\Day');

        $query = $this->createQueryBuilder('c');

	    $query->select('c')
		       ->where('c.createdAt >= :startDate')
		       ->andWhere('c.createdAt <= :endDate');

		$query->setParameter('startDate', $startDate)
		    ->setParameter('endDate', $endDate);		    


		try {
			return $query->getQuery()->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			dump($e);exit;
		}
    }
}
