<?php

namespace AppBundle\Repository;

/**
 * CicloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CicloRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByDate($startDate, $endDate)
    {	

		$query = $this->getEntityManager()
		   	->createQuery('
				SELECT c 
				FROM AppBundle:Ciclo c
				WHERE c.createdAt >= :startDate AND c.updatedAt <= :endDate
			')
		    ->setParameter('startDate', $startDate)
		    ->setParameter('endDate', $endDate);

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			dump($e);exit;
		}
    }
}
