<?php

namespace AppBundle\Repository;

/**
 * ColheitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColheitaRepository extends \Doctrine\ORM\EntityRepository
{
}
