<?php

namespace AppBundle\Repository;

/**
 * EstufaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstufaRepository extends \Doctrine\ORM\EntityRepository
{
}
