<?php

namespace AppBundle\Repository;

/**
 * NutrienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutrienteRepository extends \Doctrine\ORM\EntityRepository
{
}
