<?php

namespace AppBundle\Repository;

/**
 * SementeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SementeRepository extends \Doctrine\ORM\EntityRepository
{
}
