<?php

namespace AppBundle\Repository;

/**
 * SementeiraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SementeiraRepository extends \Doctrine\ORM\EntityRepository
{
}
