<?php

namespace AppBundle\Repository;

/**
 * TanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
