<?php

namespace AppBundle\Repository;

/**
 * TanquesNutrientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TanquesNutrientesRepository extends \Doctrine\ORM\EntityRepository
{
}
