<?php

namespace AppBundle\Repository;

/**
 * TratamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
