fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

estufa_ana:
    path: /estufa/ana 
    defaults:  { _controller: AppBundle:Default:estufaAna }

estufa_cat:
    path: /estufa/catarina
    defaults:  { _controller: AppBundle:Default:estufaCat }

mesa:
    path: /estufa/{type}/mesa/{id}
    defaults:  { _controller: AppBundle:Default:mesa }

produtos:
    path: /produtos
    defaults:  { _controller: AppBundle:Default:produtos }

produto:
    path: /produtos/{id}
    defaults:  { _controller: AppBundle:Default:produto }

add_produto:
    path: /produto/add
    defaults:  { _controller: AppBundle:Default:addProduto }

logout:
    path: /logout