app:
    resource: '@AppBundle/Controller/'
    type: annotation

estufa_ana:
    path: /estufa/ana 
    defaults:  { _controller: AppBundle:Default:estufaAna }

estufa_cat:
    path: /estufa/catarina
    defaults:  { _controller: AppBundle:Default:estufaCat }

mesa:
    path: /estufa/{type}/mesa/{id}
    defaults:  { _controller: AppBundle:Default:mesa }