# Disable rest, profile, register
fos_user_registration:
    path: /register
    defaults: { _controller: "FOSUserBundle:Security:login" }
    
fos_user_resetting:
    path: /resetting
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_password:
    path: /profile
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_security_login:
    path: /login
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: "FOSUserBundle:Security:loginCheck"}

fos_user_security_logout:
    path: /logout
    defaults: { _controller: "FOSUserBundle:Security:logout"}
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:  { _controller: AppBundle:Default:index }    

estufa:
    path: /estufa/{type}
    defaults:  { _controller: AppBundle:Default:estufa }

mesa:
    path: /estufa/{type}/mesas/{id}
    defaults:  { _controller: AppBundle:Default:mesa }

produtos:
    path: /produtos
    defaults:  { _controller: AppBundle:Default:produtos }

produto:
    path: /produtos/{id}
    defaults:  { _controller: AppBundle:Default:produto }

add_produto:
    path: /produto/add
    defaults:  { _controller: AppBundle:Default:addProduto }

semente:
    path: /sementes/{id}
    defaults:  { _controller: AppBundle:Default:semente }

sementes:
    path: /sementes
    defaults:  { _controller: AppBundle:Default:sementes }

    
add_sementeira:
    path: /sementeira/add
    defaults:  { _controller: AppBundle:Default:addSementeira }
       
          
sementeiras:
    path: /sementeiras
    defaults:  { _controller: AppBundle:Default:sementeiras }
    
sementeira:
    path: /sementeira/{id}
    defaults:  { _controller: AppBundle:Default:sementeira }

add_semente:
    path: /semente/add
    defaults:  { _controller: AppBundle:Default:addSemente }

tanque:
    path: /tanques/{id}
    defaults:  { _controller: AppBundle:Default:tanque }

tanques:
    path: /tanques
    defaults:  { _controller: AppBundle:Default:tanques }

add_tanque:
    path: /tanque/add
    defaults:  { _controller: AppBundle:Default:addTanque }

nutriente:
    path: /nutrientes/{id}
    defaults:  { _controller: AppBundle:Default:nutriente }

nutrientes:
    path: /nutrientes
    defaults:  { _controller: AppBundle:Default:nutrientes }

add_nutriente:
    path: /nutriente/add
    defaults:  { _controller: AppBundle:Default:addNutriente }

export_mesas:
    path: /mesas/export
    defaults:  { _controller: AppBundle:Default:export }

print_ciclo:
    path: /mesas/export/ciclos/print/{id}
    defaults:  { _controller: AppBundle:Default:exportCiclo }

print_month:
    path: /mesas/export/ciclos/print/{id}/year/{year}/month/{month}
    defaults:  { _controller: AppBundle:Default:exportMonth }

qrcode:
    path: /qrcode/list
    defaults:  { _controller: AppBundle:Default:qrcodeList }

qrc_print_all:
    path: /qrcode/print/all
    defaults:  { _controller: AppBundle:Default:qrcPrtAll }

qrcode_print:
    path: /qrcode/print/{id}
    defaults:  { _controller: AppBundle:Default:qrcodePrintOne }


EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode