# Disable rest, profile, register
fos_user_registration:
    path: /register
    defaults: { _controller: "FOSUserBundle:Security:login" }
    
fos_user_resetting:
    path: /resetting
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_password:
    path: /profile
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_security_login:
    path: /login
    defaults: { _controller: "FOSUserBundle:Security:login" }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: "FOSUserBundle:Security:loginCheck"}

fos_user_security_logout:
    path: /logout
    defaults: { _controller: "FOSUserBundle:Security:logout"}
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation

estufa:
    path: /estufa/{type}
    defaults:  { _controller: AppBundle:Default:estufa }

mesa:
    path: /estufa/{type}/mesas/{id}
    defaults:  { _controller: AppBundle:Default:mesa }

produtos:
    path: /produtos
    defaults:  { _controller: AppBundle:Default:produtos }

produto:
    path: /produtos/{id}
    defaults:  { _controller: AppBundle:Default:produto }

add_produto:
    path: /produto/add
    defaults:  { _controller: AppBundle:Default:addProduto }

export_mesas:
    path: /mesas/export
    defaults:  { _controller: AppBundle:Default:export }

print_ciclo:
    path: /ciclos/print/{id}
    defaults:  { _controller: AppBundle:Default:print }