AppBundle\Entity\Colheita:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ColheitaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        kg:
            type: integer
    manyToOne:
        ciclo:
            targetEntity: Ciclo
            inversedBy: colheitas
            joinColumn:
                name: ciclo_id
                referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [ ]
        preUpdate: [  ]
