AppBundle\Entity\Estufa:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EstufaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        qrcode:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
