AppBundle\Entity\Sementeira:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SementeiraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        endedAt:
            type: datetime
            nullable: true
        quantitade:
            type: integer
    manyToOne:
        type:
            targetEntity: Semente
            cascade:      [persist]
            joinColumn:
                name: semente_id
                referencedColumnName: id
    oneToOne:
      ciclo:
        targetEntity: Ciclo
        inversedBy: sementeira
        joinColumn:
          name: ciclo_id
          referencedColumnName: id
          nullable: true
