AppBundle\Entity\TanquesNutrientes:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TanquesNutrientesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        kg:
            type: integer
            nullable: true
            options:
                default: 0
    manyToOne:
        tanque:
            targetEntity: Tanque
            inversedBy: nutrientes
            joinColumn:
                name: tanque_id
                referencedColumnName: id
        nutriente:
            targetEntity: Nutriente
            cascade:      [persist]
            joinColumn:
                name: nutriente_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAt,setUpdatedAt ]
        preUpdate: [ setUpdatedAt ]
