AppBundle\Entity\Tratamento:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TratamentoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime  
        endedAt:
            type: datetime 
        isEnded:
            type: boolean
            options:
                default: 0
    manyToOne:
        produto:
            targetEntity: Produto
            cascade:      [persist]
            joinColumn:
                name: produto_id
                referencedColumnName: id
        ciclo:
            targetEntity: Ciclo
            inversedBy: tratamentos
            joinColumn:
                name: ciclo_id
                referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [ setCreatedAt, setInitialEndedAt ]
        preUpdate: [  ]
