<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mesa extends \AppBundle\Entity\Mesa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'qrcode', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'ciclos', 'ciclo'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'qrcode', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Mesa' . "\0" . 'ciclos', 'ciclo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mesa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setQrcode($qrcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQrcode', [$qrcode]);

        return parent::setQrcode($qrcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getQrcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQrcode', []);

        return parent::getQrcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addCiclo(\AppBundle\Entity\Ciclo $ciclo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCiclo', [$ciclo]);

        return parent::addCiclo($ciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCiclo(\AppBundle\Entity\Ciclo $ciclo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCiclo', [$ciclo]);

        return parent::removeCiclo($ciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiclos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiclos', []);

        return parent::getCiclos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPastCiclo(\AppBundle\Entity\Ciclo $ciclo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPastCiclo', [$ciclo]);

        return parent::addPastCiclo($ciclo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPastCiclos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPastCiclos', []);

        return parent::getPastCiclos();
    }

    /**
     * {@inheritDoc}
     */
    public function getCiclo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiclo', []);

        return parent::getCiclo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiclo(\AppBundle\Entity\Ciclo $ciclo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiclo', [$ciclo]);

        return parent::setCiclo($ciclo);
    }

}
